### ISSUE TITLE
Allow selecting remote branches when creating worktrees.

### ISSUE THREAD

**Issue by airtonix** [CodeInKlingon/vscode-git-worktree#1]
Amazing! Good work on executing the seemingly impossible.

- see a list of worktrees
- selecting a parent folder
- allowing for worktree folder name to be different from branch name

One feature I'd ask for is that instead of only showing locally checked out branches as candidates for creating new worktrees from, also include remotes too. 🙏🏻

**Comment by CodeInKlingon** [comment]
Thank you so much for your feedback! That is a great suggestion and something I overlooked. I've just released a new version that hopefully addresses this. v1.0.1 If you have any issues or other suggestions please let me know.

**Comment by airtonix** [comment]
Legend 🦾 Great stuff!
