### ISSUE TITLE
provide an alternative display format

### ISSUE THREAD

**Issue by airtonix** [CodeInKlingon/vscode-git-worktree#4]
When branch names become long, it becomes harder to see the worktree path.

current display format: 

```
{branchName} <dim>{worktreePath}</dim>
```

alternative display format? 

```
{branchName}
<dim>{worktreePath}</dim>
```

bonus points if this can just be a multiline text field in user preferences

**Comment by CodeInKlingon** [comment]
Unfortunately the vscode TreeItem api that is used is quite limited. From my understanding the current display format is all that is permitted; a title, a description and a tooltip.  I appreciate your suggestion though. I too have found it frustrating sometimes to see the file path when the branch name is long. I'm open to other suggestions.
